export interface CountryData {
  code: string;
  name: string;
  dial_code: string;
}

export const COUNTRIES: CountryData[] = [
  { code: 'AF', name: 'Afghanistan', dial_code: '+93' },
  { code: 'AL', name: 'Albania', dial_code: '+355' },
  { code: 'DZ', name: 'Algeria', dial_code: '+213' },
  { code: 'AR', name: 'Argentina', dial_code: '+54' },
  { code: 'AU', name: 'Australia', dial_code: '+61' },
  { code: 'AT', name: 'Austria', dial_code: '+43' },
  { code: 'BD', name: 'Bangladesh', dial_code: '+880' },
  { code: 'BE', name: 'Belgium', dial_code: '+32' },
  { code: 'BR', name: 'Brazil', dial_code: '+55' },
  { code: 'CA', name: 'Canada', dial_code: '+1' },
  { code: 'CL', name: 'Chile', dial_code: '+56' },
  { code: 'CN', name: 'China', dial_code: '+86' },
  { code: 'CO', name: 'Colombia', dial_code: '+57' },
  { code: 'DK', name: 'Denmark', dial_code: '+45' },
  { code: 'EG', name: 'Egypt', dial_code: '+20' },
  { code: 'FI', name: 'Finland', dial_code: '+358' },
  { code: 'FR', name: 'France', dial_code: '+33' },
  { code: 'DE', name: 'Germany', dial_code: '+49' },
  { code: 'GR', name: 'Greece', dial_code: '+30' },
  { code: 'IN', name: 'India', dial_code: '+91' },
  { code: 'ID', name: 'Indonesia', dial_code: '+62' },
  { code: 'IR', name: 'Iran', dial_code: '+98' },
  { code: 'IQ', name: 'Iraq', dial_code: '+964' },
  { code: 'IE', name: 'Ireland', dial_code: '+353' },
  { code: 'IL', name: 'Israel', dial_code: '+972' },
  { code: 'IT', name: 'Italy', dial_code: '+39' },
  { code: 'JP', name: 'Japan', dial_code: '+81' },
  { code: 'KE', name: 'Kenya', dial_code: '+254' },
  { code: 'KR', name: 'South Korea', dial_code: '+82' },
  { code: 'MY', name: 'Malaysia', dial_code: '+60' },
  { code: 'MX', name: 'Mexico', dial_code: '+52' },
  { code: 'MA', name: 'Morocco', dial_code: '+212' },
  { code: 'NL', name: 'Netherlands', dial_code: '+31' },
  { code: 'NZ', name: 'New Zealand', dial_code: '+64' },
  { code: 'NG', name: 'Nigeria', dial_code: '+234' },
  { code: 'NO', name: 'Norway', dial_code: '+47' },
  { code: 'PK', name: 'Pakistan', dial_code: '+92' },
  { code: 'PE', name: 'Peru', dial_code: '+51' },
  { code: 'PH', name: 'Philippines', dial_code: '+63' },
  { code: 'PL', name: 'Poland', dial_code: '+48' },
  { code: 'PT', name: 'Portugal', dial_code: '+351' },
  { code: 'RO', name: 'Romania', dial_code: '+40' },
  { code: 'RU', name: 'Russia', dial_code: '+7' },
  { code: 'SA', name: 'Saudi Arabia', dial_code: '+966' },
  { code: 'SG', name: 'Singapore', dial_code: '+65' },
  { code: 'ZA', name: 'South Africa', dial_code: '+27' },
  { code: 'ES', name: 'Spain', dial_code: '+34' },
  { code: 'LK', name: 'Sri Lanka', dial_code: '+94' },
  { code: 'SE', name: 'Sweden', dial_code: '+46' },
  { code: 'CH', name: 'Switzerland', dial_code: '+41' },
  { code: 'TW', name: 'Taiwan', dial_code: '+886' },
  { code: 'TH', name: 'Thailand', dial_code: '+66' },
  { code: 'TR', name: 'Turkey', dial_code: '+90' },
  { code: 'UA', name: 'Ukraine', dial_code: '+380' },
  { code: 'AE', name: 'United Arab Emirates', dial_code: '+971' },
  { code: 'GB', name: 'United Kingdom', dial_code: '+44' },
  { code: 'US', name: 'United States', dial_code: '+1' },
  { code: 'VN', name: 'Vietnam', dial_code: '+84' }
].sort((a, b) => a.name.localeCompare(b.name));
